### ISSUE TITLE
LMS error payload sends either `message` and `error_message`

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#1741] opened 2020-05-12 16:19 UTC
~~If for any reason apiCall returns a 500 error, it will put the UI in a state to re-request authorization. This is somewhat meaningless and any re-request would likely result in the same error over and over. In this case we should instead put the UI into the `error-report-submission` state where it informs the user to reload the page.~~

**Update**

Updating this ticket to focus only on fixing error payload. Errors returned from LMS should have a variable `message` but not `error_message` 

Currently the client does not handle both cases correctly due to a logical bug in `utils/api.js` and moreso, we don't need to handle both cases but rather should just have 1 consistent way of packaging the error.

**Comment by jon-betts** [comment] 2020-05-19 14:22
Quick note on HTTP statuses, I think practically you're right. If it's dead it's probably going to be dead the next time.

Semantically though 5xx errors suggest that retrying _might_ actually work. 4xx errors are to say it _definitely_ won't. 

It might be good to see what the error is in case it really should be something else. What's the error condition?

**Comment by seanh** [comment] 2020-06-27 13:53
> If for any reason apiCall returns a 500 error, it will put the UI in a state to re-request authorization. This is somewhat meaningless and any re-request would likely result in the same error over and over. In this case we should instead put the UI into the error-report-submission state where it informs the user to reload the page.

I don't think this is correct. Showing an error dialog with a **Try again** button was deliberate and by design. What the **Try again** button does is try the whole process again from the start in order to give things the best chance of succeeding on re-try: beginning with getting a brand new access token (in case there was anything wrong with the access or refresh token, there are many things wrong with these) and then re-doing the action (launching the assignment or whatever) with the new access token.

In many cases when there is a 500 error this re-try will in fact succeed.

In some cases it may not succeed--for example if our code simply has a bug that means it's going to fail every time. But we can't detect those cases. Putting the user in an infinite **Try again** loop but with an error dialog that says **If the problem persists...** (followed by support links) was a deliberate design decision.

It looks to me like there isn't an issue to fix here? I think the suggested fix would take a deliberate behaviour and make it worse: removing the **Try again** button deprives users of the ability to kick off a re-try that would sometimes succeed.

> Semantically though 5xx errors suggest that retrying might actually work. 4xx errors are to say it definitely won't.

I actually don't think it's true that _4xx errors are to say it definitely won't_ (succeed) on re-try either. Given that re-trying gets a whole new access token from scratch and then re-tries, it could in fact succeed.

**Comment by seanh** [comment] 2020-06-27 13:55
@jon-betts @LMS007 I think the current behaviour on production is correct, suggest closing this issue?

**Closed** 2020-08-03 07:51 UTC
Labels: Bug
