### ISSUE TITLE
Intermittent PDF.js error when loading Canvas assignments created with Canvas PDFs

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#890] opened 2019-08-13 19:35 UTC
## Description
Intermittently when loading a PDF in Canvas, the file fails to load and a pdf.js error popup appears. This does not happen every time - you may need to reload to reproduce. This seems to be isolated to PDFs that are added via the Canvas file picker.

## Details
- We've reproduced this issue in latest versions of Chrome and FF for Mac; unable to repro in Safari
- Seems to be isolated to Canvas File Picker PDFs; adding the same PDF via Google Picker does not lead to the error message
- Cannot repro with the same PDF using local annotation + Chrome extension, or hosting the PDF on WP and using Via to annotate - so this seems to be isolated to the LMS environment
- Also haven't been able to repro with other PDFs

The popup's error message is:

> PDF.js v1.1.24 (build: f6a8110)
> Message: Unexpected server response (206) while retrieving PDF “https://via.hypothes.is/id_/https://cdn.inst-fs-iad-prod.inscloudgate.net/9c90a7f1-a381-4ca9-9894-a8c500c8a47c/The%20Bluest%20Eye%20(excerpt).pdf?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImNkbiJ9.eyJyZXNvdXJjZSI6Ii85YzkwYTdmMS1hMzgxLTRjYTktOTg5NC1hOGM1MDBjOGE0N2MvVGhlJTIwQmx1ZXN0JTIwRXllJTIwKGV4Y2VycHQpLnBkZiIsImlhdCI6MTU2NTY4NDYzOCwiZXhwIjoxNTY1NzcxMDM4fQ.IHXKrDW2UWVT2wngVS5Gic3_w8SBWFcVOSjO8MAlu8TnVqS1O24L_5CNnLkbzB9jwcBpp9gLEF2mtYh3zFzs0A&content_type=application%2Fpdf“.

When this happens the console warning is:

> Warning: The provided value ‘moz-chunked-arraybuffer’ is not a valid enum value of type XMLHttpRequestResponseType.
> NetworkManager_request @ pdf.worker.js:1693
> Error: postmessage-json-rpc.js:49 Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (’https://lms.hypothes.is') does not match the recipient window’s origin (‘https://via.hypothes.is’).
> call @ postmessage-json-rpc.js:49

[The Bluest Eye (excerpt).pdf](https://github.com/hypothesis/lms/files/3498540/The.Bluest.Eye.excerpt.pdf)
![Hypothesis](https://user-images.githubusercontent.com/22603275/62971283-6b799e80-bddf-11e9-8f3b-4b5e014c1a59.png)

## Steps to reproduce
1. Upload this PDF to your Canvas file repo: https://github.com/hypothesis/support/blob/master/The-Bluest-Eye-Excerpt.pdf
2. Create an assignment using the Canvas file picker
3. Launch the assignment you've created

### Expected behavior
PDF loads with Hypothesis sidebar over it

### Actual behavior
Intermittently, this happens:
![image](https://user-images.githubusercontent.com/12087705/62972203-83522200-bde1-11e9-8143-80f2f29d7d0e.png)

and if you click to see more info, it looks like: 
![image (1)](https://user-images.githubusercontent.com/12087705/62972226-8f3de400-bde1-11e9-9ea5-10c46eaeb7eb.png)

If the error message doesn't show up, try reloading your browser tab a few times.

**Comment by xolotl** [comment] 2019-08-13 19:51
For me, wasn't so much a popup, but rather when launching the reading in another tab (which Canvas required). Truly intermittent:
1. worked
1. close window, refresh original page, open window: error
1. repeat: worked

**Comment by klemay** [comment] 2019-08-13 19:54
For the moment, we've only seen this with 1 PDF (and I haven't been able to reproduce with others). In that case, it would be useful to know: **is there anything about this PDF specifically causing this error to appear?**

**Comment by ajpeddakotla** [comment] 2019-08-13 22:13
FYI - there was a thread that @robertknight had a couple of days ago in Slack with the same error message. It seems that this may likely be an issue with PDF.js. Catch-up reading from vacation ftw! https://hypothes-is.slack.com/archives/C4K6M7P5E/p1565282068025300

**Comment by klemay** [comment] 2019-08-14 14:44
Ah good catch @ajpeddakotla! It does look like it could be related. That Slack convo is why https://github.com/hypothesis/via/issues/81 got added to the current sprint - once PDF.js is updated for Via, we should check this PDF again to see if that resolves the issue.

**Comment by robertknight** [comment] 2019-08-16 10:33
I've seen this happen with other PDFs than the one mentioned in the issue. I'm pretty sure it is specific to PDFs fetched from Canvas, or at least to files that are delivered from the same source.

**Comment by robertknight** [comment] 2019-09-09 15:09
From my initial debugging, it looks like PDF.js is making an XHR request without any `Range` header, but Chrome can end up responding with an HTTP 206 Partial Content response.

The issue can be reproduced using Via alone. I was able to reproduce using https://via.hypothes.is/https://cdn.inst-fs-iad-prod.inscloudgate.net/9c90a7f1-a381-4ca9-9894-a8c500c8a47c/The-Bluest-Eye-Excerpt.pdf?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImNkbiJ9.eyJyZXNvdXJjZSI6Ii85YzkwYTdmMS1hMzgxLTRjYTktOTg5NC1hOGM1MDBjOGE0N2MvVGhlLUJsdWVzdC1FeWUtRXhjZXJwdC5wZGYiLCJpYXQiOjE1Njc5OTU5ODgsImV4cCI6MTU2ODA4MjM4OH0.eyRztlREC1pP3fwsI2iUbEtNjlRJrccZ2NUg8iPS22GZSSCrtwm0_N_TV2PGgx_xgXAvaIMLeDaMQQTDPU55xg&content_type=application%2Fpdf . Note that this URL has a JWT which expires on 2019-09-10 so it won't work after that.

By adding logpoints around the code in PDF.js [which sends the XHR request](https://github.com/mozilla/pdf.js/blob/c9a74984ec7eca8a49d33acdf760761e3d6df989/src/core/network.js#L146) I was able to observe the following sequence:

1. PDF.js makes an XHR request with no `Range` header set and an expected status code of 200
2. PDF.js receives an XHR response with a 206 status code, which is unexpected, triggering an error.
3. The Chrome logs show the following request made by the browser:

```
:authority: via.hypothes.is
:method: GET
:path: /id_/https://cdn.inst-fs-iad-prod.inscloudgate.net/9c90a7f1-a381-4ca9-9894-a8c500c8a47c/The-Bluest-Eye-Excerpt.pdf?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImNkbiJ9.eyJyZXNvdXJjZSI6Ii85YzkwYTdmMS1hMzgxLTRjYTktOTg5NC1hOGM1MDBjOGE0N2MvVGhlLUJsdWVzdC1FeWUtRXhjZXJwdC5wZGYiLCJpYXQiOjE1Njc5OTU5ODgsImV4cCI6MTU2ODA4MjM4OH0.eyRztlREC1pP3fwsI2iUbEtNjlRJrccZ2NUg8iPS22GZSSCrtwm0_N_TV2PGgx_xgXAvaIMLeDaMQQTDPU55xg&content_type=application%2Fpdf
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en;q=0.9,es;q=0.8,en-US;q=0.7
cookie: __cfduid=d2691bc1d8b3a6275b8e3cdb3856db2f31567461230; _ga=GA1.2.2002158745.1567687611; _gid=GA1.2.94637581.1568037519
if-none-match: "fc39785e9af2f70db775016e31857a03"
range: bytes=0-801973
referer: https://via.hypothes.is/static/pdfjs/build/pdf.worker.js
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3902.4 Safari/537.36
```

Note that a `range` header has been added with a byte range which refers to the entire file, and there is an `if-none-match` header which refers to an `etag` header that was returned by a previous request for this URL which completed with a 200 response.

My understanding of [HTTP range requests](https://tools.ietf.org/html/rfc7233) is that a server is allowed to respond to a request with a `Range` header with a 200 (non-range) response if the server doesn't support range requests, but a server is not allowed to respond to a request without a `Range` header with a 206 (range/partial) response.  That could cause problems since the client might not support range responses.

When everything works normally, Chrome shows the following request and response:

Request:
```
:authority: via.hypothes.is
:method: GET
:path: /id_/https://cdn.inst-fs-iad-prod.inscloudgate.net/9c90a7f1-a381-4ca9-9894-a8c500c8a47c/The-Bluest-Eye-Excerpt.pdf?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImNkbiJ9.eyJyZXNvdXJjZSI6Ii85YzkwYTdmMS1hMzgxLTRjYTktOTg5NC1hOGM1MDBjOGE0N2MvVGhlLUJsdWVzdC1FeWUtRXhjZXJwdC5wZGYiLCJpYXQiOjE1Njc5OTU5ODgsImV4cCI6MTU2ODA4MjM4OH0.eyRztlREC1pP3fwsI2iUbEtNjlRJrccZ2NUg8iPS22GZSSCrtwm0_N_TV2PGgx_xgXAvaIMLeDaMQQTDPU55xg&content_type=application%2Fpdf
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en;q=0.9,es;q=0.8,en-US;q=0.7
cookie: __cfduid=d2691bc1d8b3a6275b8e3cdb3856db2f31567461230; _ga=GA1.2.2002158745.1567687611; _gid=GA1.2.94637581.1568037519
referer: https://via.hypothes.is/static/pdfjs/build/pdf.worker.js
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3902.4 Safari/537.36
```

Response:

```
accept-ranges: bytes
cache-control: public, max-age=86400
cf-cache-status: MISS
cf-ray: 513a11c2fdf0dc2b-LHR
content-disposition: inline; filename="The-Bluest-Eye-Excerpt.pdf"
content-length: 801974
content-type: application/pdf
date: Mon, 09 Sep 2019 15:07:02 GMT
etag: "fc39785e9af2f70db775016e31857a03"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Tue, 10 Sep 2019 15:07:02 GMT
last-modified: Tue, 13 Aug 2019 16:22:53 GMT
server: cloudflare
status: 200
strict-transport-security: max-age=15552000; includeSubDomains; preload
vary: Accept-Encoding
via: 1.1 6eaa7f856e226a0db7cef6201d3b8393.cloudfront.net (CloudFront)
x-amz-cf-id: IBCVrIj98C4fy81oLvgPgRKVlhRW5iDIyBUVkGuiJq05tntS_CcKpA==
x-amz-cf-pop: SFO20
x-amz-id-2: 6ZACP/+4gh5bGLknr0D7BgdnZP0P7QBfS0mNq1iaeN98a5mPFupURfGVLchRypBz6TylQINCGaQ=
x-amz-replication-status: COMPLETED
x-amz-request-id: E687A8A349321DF2
x-amz-server-side-encryption: AES256
x-amz-version-id: A5bV7wXAqXanBpT5F7TBnNzjtzCxauMc
x-cache: RefreshHit from cloudfront
x-content-type-options: nosniff
```

**Comment by robertknight** [comment] 2019-09-10 06:52
I filed an issue in PDF.js as I think we are going to have to deal with the problem there, even if the issue is eventually deemed to be a problem in Chrome itself.

**Comment by robertknight** [comment] 2019-09-12 04:53
I was able to reproduce the basic issue in Chrome and have reported it here: https://bugs.chromium.org/p/chromium/issues/detail?id=1003229

I was not able to reproduce the issue in Firefox or Safari using this test case.

**Comment by robertknight** [comment] 2019-09-19 11:55
The issue has been confirmed in Chrome, but there is no ETA on a fix yet.

From initial testing it looks like upgrading to PDF.js v2 will work around the issue along with providing other improvements. I've not been able to confirm exactly why yet, but it appears that PDF.js v2 does not (or is less likely to) trigger the bug in Chrome.

Therefore the plan for Hypothesis is to [upgrade Via](https://github.com/hypothesis/via/issues/81) (and any other PDF proxy we may build) to PDF.js v2, do some re-testing and if we can no longer reproduce this issue, close it.

**Comment by robertknight** [comment] 2019-09-19 14:22
The upgrade to PDF.js v2 in Via has now been deployed. I'm not able to reproduce the issue in Chrome following that, so I'm tentatively going to mark this as resolved.

**Closed by robertknight** 2019-09-19 14:22 UTC
Labels: bug
