### ISSUE TITLE
Error details aren't shown when "Error Details" button is clicked

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1824] opened 2020-06-09 13:40 UTC
Go to the [Missing Developer Key Scopes test course](https://hypothesis.instructure.com/courses/121) and launch a Canvas Files assignment. You'll be asked to authorize, and in the popup window you'll be taken to an error dialog.

Clicking on the _Error Details_ button doesn't reveal the error details. It does expand the _Error Details_ section but, since it expands off the bottom of the window, the error details aren't actually in view until the user notices that they have to scroll down.

![Peek 2020-06-09 14-39](https://user-images.githubusercontent.com/22498/84154434-04f4f980-aa5f-11ea-82aa-439ba8b75900.gif)

You can also see in this GIF that the scrollbar is shown when it isn't needed. I made a separate issue for that: https://github.com/hypothesis/lms/issues/1823

**You can also see that the width and height of the white dialog both change a little bit when the error details are expanded**, which is weird.

**Comment by robertknight** [comment] 2020-06-15 13:59
I've marked this issue as closed. However there is a caveat.

The issue is fixed in most instances of the error dialog but I realised it does not apply for the specific case of the error shown in the screenshot above because that dialog is server-rendered HTML rather than the Preact component we use it most places. As such it doesn't inherit any of the logic built into the `ErrorDialog` component.

**Comment by robertknight** [comment] 2020-06-15 14:06
I'm reopening this while I look into the above.

**Comment by robertknight** [comment] 2020-07-13 08:53
This was resolved by https://github.com/hypothesis/lms/pull/1835, which switches the dialog shown in the issue to the client-rendered one. The client rendered dialog has logic to scroll the "Error details" box into view when expanded.

**Closed by robertknight** 2020-07-13 08:53 UTC
Labels: Bug, Frontend
