### ISSUE TITLE
Spike: Does LMS provisioning work in Sakai?

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#362] opened 2018-11-29 17:37 UTC
We need to determine if the new provisioning features work in the Sakai LMS. This is a research task and will require figuring out how to set up/access a Sakai instance somewhere.

**Comment by klemay** [comment] 2018-12-04 18:09
Note on setting up a local instance: Many of Sakai's dependencies are old, and it can be hard to track down the correct versions. 

The Sakai 11 install guide is here: https://confluence.sakaiproject.org/pages/viewpage.action?pageId=106792022#Sakai11installguide(source)-1.0InstallPrerequisites

...and I'll put direct links to the dependency downloads here:

- [Java SE 8](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
- [Maven 3 archives](https://archive.apache.org/dist/maven/maven-3/) (Sakai recommends Maven 3.2.5 through 3.3.9)
- [Tomcat 8](https://tomcat.apache.org/download-80.cgi)

**Comment by xolotl** [comment] 2018-12-06 19:37
@klemay I can reach out to my erstwhile Sakai colleagues to see if there is an instance we could use for this. Before I do, I'm not clear on why the public instances (ie, was it a nightly? what URL was it at?) won't serve. If you can expand on that, I can better explain what we need.

**Comment by klemay** [comment] 2018-12-06 19:45
@xolotl That would be fantastic!

The issue with the Sakai Nightly and the Longsight instances I tried is that there isn't a consistent database attached, which messes with the way Hypothesis serves the LTI link. 

What we need is a course site where:
- There is a stable database attached (i.e., the Db doesn't reset nightly; we can make changes to the course site that will persist over time)
- H team members have Instructor-level access 
- The "Add LTI Tool" option is present in the "External Tools" tab of the site settings (some institutions disable this for Instructor-level users)

It would be _especially_ nice if we had the ability to create new course sites for testing local and QA versions of the app in the future, but that is not a "must-have."

**Comment by xolotl** [comment] 2018-12-06 19:59
@klemay so is the issue that H. _can_ test everything it needs in Sakai Nightly (can you provide the URL you are using?), but only if we complete that testing before the next db refresh and recreate it all from scratch the next time we need to test (ie, it's really inconvenient)? Or is there something about Sakai Nightly that actually makes it impossible for H. to test?

**Comment by klemay** [comment] 2018-12-06 20:03
@xolotl it is impossible to test in the Sakai Nightly instance! The Hypothesis LMS app is unable to create assignments, even if you try immediately after the install/before the nightly refresh.

**Comment by jeremydean** [comment] 2018-12-06 20:06
@klemay i have tested in nightly in the past. 

the issue i experienced is that you need to create n+1 assignments before getting the configuration screen because the nightly refresh confuses h and it presents the previous n assignments before allowing you to create a new one.

**Comment by klemay** [comment] 2018-12-06 20:09
@jeremydean I'm not even able to get that far - the nightly instance is serving me a 500 Error after the assignments have been created and I try to launch one to drop in a link to a web page.

**Comment by xolotl** [comment] 2018-12-06 20:19
I'm just trying to have the best understanding of what issues we are experiencing so that I can describe the issue and possibly find something that works. It's not yet clear to me that Nightly's database refresh is the issue. Maybe the three of us could walk through a test on Nightly together to uncover more? Also, what Nightly URL are you all using?

**Comment by jeremydean** [comment] 2018-12-06 20:23
@katelyn i just tried again and was able to get to the point where i see a hypothesis-enabled doc load and provision private group and user. (*if i did this N times i'd finally get the configuration screen.) 

i'm wondering if your 505 has to do with the key/secret used? every time i test in sakai i use the key/secret i originally created. those key/secrets are logged [here](https://docs.google.com/spreadsheets/d/1y2MIkyfw6F1pLdBdIq5IfvLTyWywAODu3AV_mAuWNpo/edit?usp=sharing). not that that should be a problem.

https://www.dropbox.com/s/c1uyj79gp3wvx15/Screenshot%202018-12-06%2014.21.45.png?dl=0
![image](https://user-images.githubusercontent.com/3261902/49609839-52704200-f962-11e8-8285-c3e486af80b5.png)

in any case, the other issue--not being able to truly create an assignment until N assignments are created--seems like it'd be worthwhile being able to test elsewhere.

**Comment by robertknight** [comment] 2018-12-11 12:35
I have created a Dockerized version of Sakai 12 to assist with local testing and development: https://github.com/hypothesis/sakai-docker.

If we need a "permanent" install of Sakai to which we have full admin access, we could deploy this to AWS.

Using this version I was able to install the production Hypothesis app.

<img width="992" alt="lms sakai" src="https://user-images.githubusercontent.com/2458/49801056-05fd7b80-fd41-11e8-9245-1e10d0576ece.png">

One caveat with this setup compared to the instructions above is that you can't currently set up a Course site directly, but you can set up a project site  and use install the LMS app into that. I think this is because the Sakai instance needs some additional configuration first.

**Comment by jeremydean** [comment] 2018-12-11 13:42
This seems amazing @robertknight . I'll let others weigh in but think it'd be great if we deployed to AWS and had a proper test instance. Is it already something I can play in or would we need to do that first.

Also, I got this from our major Sakai partner yesterday and am wondering if we can test and respond:

>I attached launch info along with the settings you get at the admin level - which shows as "Required data param for LTI launch missing: resource_link_id."

>I understand that the course-level configuration is working, but the sitewide config is not - this might be one of the Privacy / Services / Content item settings that I need to unselect. I attached the setting I have dukedev set up with right now.

>However, you can see all the admin-level external tool options and configure your own at the site level by entering "admin" for username and "admin" for password on a Sakai 12.x nightly server:
>https://qa12-mysql.nightly.sakaiproject.org/
>Just navigate to Administration workspace > External tools:
>https://qa12-mysql.nightly.sakaiproject.org/portal/site/!admin

>Is there anything else I can do to test this in the meantime? Which settings do you have configured, and which may I try to unselect?

[launch_hypothesis.txt](https://github.com/hypothesis/lms/files/2667786/launch_hypothesis.txt)

<img width="701" alt="sakai___administration_workspace___external_tools" src="https://user-images.githubusercontent.com/3261902/49804498-4b598300-fd18-11e8-9a0d-57b4345e8300.png">

**Comment by robertknight** [comment] 2018-12-11 13:45
> I understand that the course-level configuration is working, but the sitewide config is not - this might be one of the Privacy / Services / Content item settings that I need to unselect. I attached the setting I have dukedev set up with right now.

Ah, I only tested course-level set up this morning. I can take a look at that this afternoon.

**Comment by robertknight** [comment] 2018-12-11 14:48
I was able to successfully configure the Hypothesis LMS app as an external tool in the Administration Workspace using the following settings:

<img width="966" alt="screenshot 2018-12-11 14 44 48" src="https://user-images.githubusercontent.com/2458/49808035-744b3980-fd53-11e8-8210-cda1a14287eb.png">

Testing the configured tool in a Project Site, I observed that when launching viewing the tool, it makes an LTI launch request (`POST` request to https://lms.hypothes.is/lti_launches) with `resource_link_id` set to something like `content:1` in the form parameters.

**Comment by robertknight** [comment] 2018-12-11 14:49
> Also, I got this from our major Sakai partner yesterday and am wondering if we can test and respond:

Can you ask them to confirm exactly which version of Sakai they are running? I'm testing on the latest version of Sakai 12.

**Comment by jeremydean** [comment] 2018-12-17 15:33
Duke is still having issues here. And @robertknight it does seem to have to do with resource_link_ID.

The error received, upon attempting to open/configure a Hypothesis "Lesson," is "missing resource_link_id".

Here is the launch data:

BasicLTI Endpoint
https://lms.hypothes.is/lti_launches

BasicLTI Parameters:
context_id=77319a28-2b8d-49a0-81ff-ba07b47a7b25
context_label=STA.671D.001.Sp19
context_title=STA.671D.001.Sp19
context_type=CourseSection
ext_lms=sakai-12.4
ext_sakai_launch_presentation_css_url_list=https://dukedev.longsight.com/library/skin/tool_base.css,https://dukedev.longsight.com/library/skin/duke-default/tool.css?version=ae
ext_sakai_role=Instructor
ext_sakai_server=https://dukedev.longsight.com
ext_sakai_serverid=dukedev1
launch_presentation_css_url=https://dukedev.longsight.com/library/skin/tool_base.css
launch_presentation_locale=en_US
launch_presentation_return_url=https://dukedev.longsight.com/imsblis/service/return-url/site/77319a28-2b8d-49a0-81ff-ba07b47a7b25
lis_course_offering_sourcedid=025670.2.1670.1.001
lis_course_section_sourcedid=025670.2.1670.1.001
lis_person_name_family=Lorch
lis_person_name_full=Chris Lorch
lis_person_name_given=Chris
lis_person_sourcedid=cl237@duke.edu
lti_message_type=basic-lti-launch-request
lti_version=LTI-1p0
oauth_callback=about:blank
oauth_consumer_key=Hypothesisb6e71b51ffbd583a1c7a1659f9f91525
oauth_nonce=29264624649116878
oauth_signature=Cmfu1dF0RvUPFbZfP9QTFOZuUeA=
oauth_signature_method=HMAC-SHA1
oauth_timestamp=1545060223
oauth_version=1.0
resource_link_description=HypothesisTest
resource_link_id=content:114
resource_link_title=HypothesisTest
roles=Instructor,Administrator,urn:lti:instrole:ims/lis/Administrator,urn:lti:sysrole:ims/lis/Administrator
tool_consumer_info_product_family_code=sakai
tool_consumer_info_version=12.4
tool_consumer_instance_guid=dukedev.longsight.com
tool_consumer_instance_url=https://dukedev.longsight.com
user_id=315c69e3-1e55-4b1e-99db-1c0157cafa97

**Comment by klemay** [comment] 2018-12-17 16:01
@jeremydean @robertknight by default, Sakai does not make the `resource_link_id` available to External Tools. This needs to be addressed on an admin level for the instance before installing the Hypothesis app. Has Duke done this yet?

**Comment by lyzadanger** [comment] 2018-12-17 16:02
This is curious as `resource_link_id` is listed as one of the three _required_ LTI parameters: 

![image](https://user-images.githubusercontent.com/439947/50099086-3e8ed080-01eb-11e9-8999-e71b89fe398a.png)

-- https://www.eduappcenter.com/docs/basics/post_parameters

**Comment by klemay** [comment] 2018-12-17 16:06
Oh, right -- I was mistaken! It's `tool_consumer_instance_guid` that Sakai doesn't provide. Sorry!!

**Comment by jeremydean** [comment] 2018-12-17 16:07
but it does appear that the tool is NOT receiving that required param, right?

so where would one ensure that it is being sent?

**Comment by jeremydean** [comment] 2018-12-17 19:50
A couple of updates from Duke. They were able to get it working:

>I toyed around with this once more and realized that the launched tool appears, but if the frame height is tall enough, the picker URL info shows up farther down the page - so it looks like it's a blank page unless you scroll.

https://www.useloom.com/share/17d44ffe274a4689b24956db51246dd0

But there's still a couple of workflows where they do see that error:

>Sure - it's a couple places that we see the resource id error: 
"Launch configuration item" option
Shopping cart icon in rich text editor

https://www.useloom.com/share/e61574482a3b4242be1eb8fbd78d410d

The latter is kind of important as I think it offers a way around using the Lessons workflow that we've been relying on but UVA is adverse to. I'm talking to them today though so will get further feedback.

**Comment by jeremydean** [comment] 2018-12-17 21:13
We may want to split this into a few separate tickets as I have one last piece of feedback from Duke:

>Is there a way to show the picker at the top / top left side of the page, so that new users don't need to know to scroll down?

>Setting the default frame height at the admin level External Tool configuration doesn't apply to Lessons, unfortunately - even if it did, that unfortunately limits how much of the tool users can see.

This seems a UX issue within the existing workflow--something I've noticed in my own use.

**Comment by robertknight** [comment] 2019-01-03 18:16
> I toyed around with this once more and realized that the launched tool appears, but if the frame height is tall enough, the picker URL info shows up farther down the page - so it looks like it's a blank page unless you scroll.

Hi @jeremydean - this feedback seems applicable to all LMSes and is something that can be worked on independently. Would you mind filing this as a separate issue?

**Comment by jeremydean** [comment] 2019-01-03 22:38
@robertknight did my best here:

https://github.com/hypothesis/lms/issues/407

**Comment by robertknight** [comment] 2019-02-05 15:12
> The error received, upon attempting to open/configure a Hypothesis "Lesson," is "missing resource_link_id".

Did Duke get Hypothesis working in Sakai in the end? `resource_link_id` appears in the launch data you posted in the comment, so the message doesn't make sense. Is the person dealing with this on their end a teacher or IT admin?

**Comment by klemay** [comment] 2019-02-05 15:38
It looks like they have it working using our suggested workflow (Lessons > Add Content > External Tool > select Hypothesis from list of available external tools) but not using the workflow they were hoping to employ (Lessons > Add Content > Add Text > add Hypothesis from Sakai's rich text editor). 

When they try to use the rich text editor workflow, they receive an error saying `resource_link_id` is missing. I think this is because they go through the whole document selection process before the Lesson item is fully created, so it hasn't been assigned a `resource_link_id` yet. 

@jeremydean I would be interested to see what happened if in the Duke instance, they:
- Went to Lessons > Add Content > Add Text and added some placeholder text.
- Save the Lessons item
- Edit the Lessons item, then try to add Hypothesis from the rich text editor
I'm guessing if they go through the entire process of creating a Lessons item and _then_ try to add 
a Hypothesis reading to it, it'll work.

**Comment by robertknight** [comment] 2019-02-07 15:23
OK, I think the next steps here would be for someone (probably me) to confirm what @klemay reported above where Hypothesis works with Sakai using the first workflow but not the second workflow. Once that is confirmed, I think we can close this and create a separate issue to track the non-working workflow.

The Dockerized version I used for testing is in https://github.com/hypothesis/sakai-docker

**Comment by robertknight** [comment] 2019-02-25 13:23
I was able to reproduce the issue @klemay described with a `resource_link_id` related error locally using our [Sakai Docker image](https://github.com/hypothesis/sakai-docker) as follows:

1. Create a new project Site in the Sakai instance
2. Go to Site Info => Manage Tools and enable the Lessons tool for the site
3. Go to the Lessons tool and select Add Content => Add Text
4. Click the "Insert ContentItem" toolbar icon, which looks like a shopping trolley <img width="156" alt="screenshot 2019-02-25 12 58 21" src="https://user-images.githubusercontent.com/2458/53339034-0eeff900-38fd-11e9-9c0b-6b02da51211f.png">

This results in a popup dialog appearing like so:

<img width="500" alt="screenshot 2019-02-25 12 55 17" src="https://user-images.githubusercontent.com/2458/53339057-1b745180-38fd-11e9-8e7e-4e1a36bd3e9b.png">

The launch request copied as cURL from the browser dev tools was:

```
curl 'https://lms.hypothes.is/lti_launches' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-GB,en;q=0.5' --compressed -H 'Referer: http://localhost:8080/access/basiclti/site/d84753d9-4954-4ad2-9626-2c7f65a89b6a/tool:1?contentReturn=http%3A%2F%2Flocalhost%3A8080%2Fportal%2Ftool%2Fbebb6580-3206-4954-90ad-9643d5fadd47%2Fsakai.basiclti.admin.helper.helper%3FeventSubmit_doContentItemEditorHandle%3DSave%26sakai.session%3Daeff10dd-5c0e-41c5-bf5b-82eaeacac185.c403d11d3eed%26panel%3DPostContentItem%26tool_id%3D1%26sakai_csrf_token%3Dbe34f89fe0346ecffba33d05f7acd0f836ef7cdd909bb0efc06f40455ed004cb&accept_media_types=*%2F*&remember=the+answer+is+42' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Connection: keep-alive' -H 'Cookie: __cfduid=dd06f0a725305b1447112d212bc350e931551098581; G_ENABLED_IDPS=google' -H 'Upgrade-Insecure-Requests: 1' --data 'tool_consumer_info_product_family_code=sakai&data=%7B%22remember%22%3A%22the+answer+is+42%22%7D&context_title=Project+2&lis_person_name_family=Administrator&roles=Instructor%2CAdministrator%2Curn%3Alti%3Ainstrole%3Aims%2Flis%2FAdministrator%2Curn%3Alti%3Asysrole%3Aims%2Flis%2FAdministrator&tool_consumer_instance_guid=sakai.hypothes.is&accept_media_types=*%2F*&oauth_signature_method=HMAC-SHA1&oauth_version=1.0&accept_copy_advice=false&ext_sakai_launch_presentation_css_url_list=http%3A%2F%2Flocalhost%3A8080%2Flibrary%2Fskin%2Ftool_base.css%2Chttp%3A%2F%2Flocalhost%3A8080%2Flibrary%2Fskin%2Fmorpheus-default%2Ftool.css%3Fversion%3DSakai&context_type=Group&lis_course_offering_sourcedid=d84753d9-4954-4ad2-9626-2c7f65a89b6a&accept_presentation_document_targets=iframe%2Cwindow&ext_lms=sakai-12-SNAPSHOT&lti_version=LTI-1p0&ext_sakai_role=maintain&content_item_return_url=http%3A%2F%2Flocalhost%3A8080%2Fportal%2Ftool%2Fbebb6580-3206-4954-90ad-9643d5fadd47%2Fsakai.basiclti.admin.helper.helper%3FeventSubmit_doContentItemEditorHandle%3DSave%26sakai.session%3Daeff10dd-5c0e-41c5-bf5b-82eaeacac185.c403d11d3eed%26panel%3DPostContentItem%26tool_id%3D1%26sakai_csrf_token%3Dbe34f89fe0346ecffba33d05f7acd0f836ef7cdd909bb0efc06f40455ed004cb&oauth_signature=ztCW7alx9EOsDtElE%2FE1%2BkGDUEg%3D&lis_course_section_sourcedid=d84753d9-4954-4ad2-9626-2c7f65a89b6a&oauth_consumer_key=Hypothesisb3561ed02d422f289177260c05fbd276&launch_presentation_locale=en&ext_sakai_serverid=c403d11d3eed&oauth_timestamp=1551099576&lis_person_sourcedid=admin&lis_person_name_full=Sakai+Administrator&launch_presentation_css_url=http%3A%2F%2Flocalhost%3A8080%2Flibrary%2Fskin%2Ftool_base.css&lis_person_name_given=Sakai&ext_sakai_server=http%3A%2F%2Flocalhost%3A8080&oauth_nonce=288406231469094&oauth_callback=about%3Ablank&user_id=admin&lti_message_type=ContentItemSelectionRequest&tool_consumer_info_version=12-SNAPSHOT&context_id=d84753d9-4954-4ad2-9626-2c7f65a89b6a&accept_multiple=false&can_confirm=false&accept_unsigned=true&context_label=Project+2&auto_create=true'
```

The form post data from that request was:

```
tool_consumer_info_product_family_code=sakai
data={"remember":"the+answer+is+42"}
context_title=Project+2
lis_person_name_family=Administrator
roles=Instructor,Administrator,urn:lti:instrole:ims/lis/Administrator,urn:lti:sysrole:ims/lis/Administrator
tool_consumer_instance_guid=sakai.hypothes.is
accept_media_types=*/*
oauth_signature_method=HMAC-SHA1
oauth_version=1.0
accept_copy_advice=false
ext_sakai_launch_presentation_css_url_list=http://localhost:8080/library/skin/tool_base.css,http://localhost:8080/library/skin/morpheus-default/tool.css?version=Sakai
context_type=Group
lis_course_offering_sourcedid=d84753d9-4954-4ad2-9626-2c7f65a89b6a
accept_presentation_document_targets=iframe,window
ext_lms=sakai-12-SNAPSHOT
lti_version=LTI-1p0
ext_sakai_role=maintain
content_item_return_url=http://localhost:8080/portal/tool/bebb6580-3206-4954-90ad-9643d5fadd47/sakai.basiclti.admin.helper.helper?eventSubmit_doContentItemEditorHandle=Save&sakai.session=aeff10dd-5c0e-41c5-bf5b-82eaeacac185.c403d11d3eed&panel=PostContentItem&tool_id=1&sakai_csrf_token=be34f89fe0346ecffba33d05f7acd0f836ef7cdd909bb0efc06f40455ed004cb
oauth_signature=ztCW7alx9EOsDtElE/E1+kGDUEg=
lis_course_section_sourcedid=d84753d9-4954-4ad2-9626-2c7f65a89b6a
oauth_consumer_key=Hypothesisb3561ed02d422f289177260c05fbd276
launch_presentation_locale=en
ext_sakai_serverid=c403d11d3eed
oauth_timestamp=1551099576
lis_person_sourcedid=admin
lis_person_name_full=Sakai+Administrator
launch_presentation_css_url=http://localhost:8080/library/skin/tool_base.css
lis_person_name_given=Sakai
ext_sakai_server=http://localhost:8080
oauth_nonce=288406231469094
oauth_callback=about:blank
user_id=admin
lti_message_type=ContentItemSelectionRequest
tool_consumer_info_version=12-SNAPSHOT
context_id=d84753d9-4954-4ad2-9626-2c7f65a89b6a
accept_multiple=false
can_confirm=false
accept_unsigned=true
context_label=Project+2
auto_create=true
```

Looking at the above list, `context_id` is a unique key for the "Site" within Sakai. Each item in the Lessons tool also has an `item_id` which appears to be an integer key that increases for each item added to the course. Unfortunately that `item_id` is. not present in the above list.

If you use the Lessons > Add Content > External Tool flow, as Katelyn described above, this works. In that case Sakai makes a request to the `/lti_launches` URL which has this POST data, including the item ID in the `resource_link_id` field:

```
tool_consumer_info_product_family_code=sakai
resource_link_title=Another+use+of+Hypothesis
context_title=Project+2
roles=Instructor,Administrator,urn:lti:instrole:ims/lis/Administrator,urn:lti:sysrole:ims/lis/Administrator
lis_person_name_family=Administrator
tool_consumer_instance_guid=sakai.hypothes.is
resource_link_id=content:7
oauth_signature_method=HMAC-SHA1
oauth_version=1.0
ext_sakai_launch_presentation_css_url_list=http://localhost:8080/library/skin/tool_base.css,http://localhost:8080/library/skin/morpheus-default/tool.css?version=Sakai
launch_presentation_return_url=http://localhost:8080/imsblis/service/return-url/site/d84753d9-4954-4ad2-9626-2c7f65a89b6a
context_type=Group
resource_link_description=Another+use+of+Hypothesis
lis_course_offering_sourcedid=d84753d9-4954-4ad2-9626-2c7f65a89b6a
ext_lms=sakai-12-SNAPSHOT
ext_sakai_role=maintain
lti_version=LTI-1p0
oauth_signature=O7EA9zLLbpTEvvgLZHvLL3AalDM=
lis_course_section_sourcedid=d84753d9-4954-4ad2-9626-2c7f65a89b6a
oauth_consumer_key=Hypothesisb3561ed02d422f289177260c05fbd276
launch_presentation_locale=en
ext_sakai_serverid=c403d11d3eed
lis_person_sourcedid=admin
oauth_timestamp=1551100237
lis_person_name_full=Sakai+Administrator
launch_presentation_css_url=http://localhost:8080/library/skin/tool_base.css
lis_person_name_given=Sakai
ext_sakai_server=http://localhost:8080
oauth_nonce=289067416356594
user_id=admin
lti_message_type=basic-lti-launch-request
oauth_callback=about:blank
tool_consumer_info_version=12-SNAPSHOT
context_id=d84753d9-4954-4ad2-9626-2c7f65a89b6a
context_label=Project+2
```

What Hypothesis needs `resource_link_id` for, AFAIK, is to serve as a key to identify the item within the course, so that when the user goes back to the item, they see the right content.

Unfortunately it doesn't look the necessary information to construct that kind of key is present in the request when `resource_link_id` is missing. I checked the HTTP referrer in case it was included there, but didn't see it. We might be able to come up with some alternate workflow to work around this, but it doesn't look like it will be trivial to solve.

One thing we could perhaps do in the interim is to provide a friendlier message to the user if they stumble into this path.

**Closed by robertknight** 2019-02-25 13:23 UTC

**Comment by robertknight** [comment] 2019-02-25 13:26
> OK, I think the next steps here would be for someone (probably me) to confirm what @klemay reported above where Hypothesis works with Sakai using the first workflow but not the second workflow.

This is done now. The TL;DR is that the LMS app does work in Sakai, but there are two issues we found that could be confusing for users:

1. You can't insert Hypothesis assignments in the middle of a text block when preparing a lesson. This is because Sakai doesn't provide us with a unique identifier for that placement of Hypothesis which we need in order to remember which content the user selected.
2. There is a confusing issue where the content item selection dialog may appear to be completely blank to the user (see 
https://github.com/hypothesis/lms/issues/407#issuecomment-466999852). That I think can be fixed quite easily.

**Comment by chrislorch** [comment] 2019-03-04 20:54
Hoped to jump in here:

One issue remains: Google picker through "Insert ContentItem"/shopping cart doesn't work or times out:
https://www.useloom.com/share/48648486310c4937994fab207dadc94c

Apart from this and #407 this is generally working - as long as the user does not choose "Launch External Tool Configuration." I've asked the community how we can hide that option for specific tools like this.

I've not tested inserting Hypothesis assignments in the middle of a text block when preparing a lesson. Has anyone seen a Sakai JIRA for this issue? I can help submit this, if not.

To clarify the above: PDF works ok through "Insert ContentItem"/ shopping cart icon.
https://www.useloom.com/share/9163def07b0f4259be2d1ac5a2911cf1
Google picker does not, as specified above.
