### ISSUE TITLE
App with provisioning not working with Wikipedia links unless a training `/` is added

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#375] opened 2018-12-05 17:19 UTC
## Steps to reproduce
1. In our Hypothesis 101 Canvas course site, create an assignment or module item using a Wikipedia link (i.e. `https://en.wikipedia.org/wiki/Golden_Retriever`)
2. Save the assignment/module item and attempt to launch it

## Expected behavior
The module item or assignment loads with the Hypothesis sidebar enabled

## Actual behavior
The Wikipedia page will load within the frame, but the Hypothesis sidebar does not appear:
<img width="1436" alt="screen shot 2018-12-05 at 12 11 01 pm" src="https://user-images.githubusercontent.com/12087705/49530752-dc4add00-f886-11e8-8756-801abedda2ae.png">

Here's a screenshot of the console:
<img width="1193" alt="screen shot 2018-12-05 at 12 12 16 pm" src="https://user-images.githubusercontent.com/12087705/49530851-10be9900-f887-11e8-9d1e-7c09122a29f8.png">

## Notes
Interestingly, if you edit the assignment or module item and add a trailing slash to the end of the Wikipedia URL, the sidebar will load, but Wikipedia will return an error because it'll search for `Golden Retriever/` in this case. 

The same module item using `https://en.wikipedia.org/wiki/Golden_Retriever/` as the url:
<img width="1448" alt="screen shot 2018-12-05 at 12 15 55 pm" src="https://user-images.githubusercontent.com/12087705/49531098-95111c00-f887-11e8-8be2-a4542260fc13.png">

This trailing slash error seems to be unique to Wikipedia. I can successfully create assignments and module items using:

- http://example.com
- https://cnn.com
- https://web.hypothes.is/blog/how-annotation-enables-machine-learning

**Comment by robertknight** [comment] 2018-12-05 20:38
The issue appears to be connected to Via and Wikipedia article pages, and is not specific to the LMS app.

The Wikipedia page contains `<link>` tags in the body like this:

<img width="832" alt="wikipedia-mw-link" src="https://user-images.githubusercontent.com/2458/49542107-84cf6000-f8cc-11e8-8ae3-aa9b06134059.png">

On startup, the client tries to resolve the absolute URL of all URLs mentioned in `<link>` elements on the page [using a normalizeURI function](https://github.com/hypothesis/client/blob/3c7e9ddd0b44a18519a9bc7a214e4fe41d4d89e4/src/annotator/plugin/document.js#L252)

When processing these links, the `link.href` property ("t" in these screenshots) matches the HTML when using the extension:

<img width="427" alt="extension-mw-link" src="https://user-images.githubusercontent.com/2458/49542205-d677ea80-f8cc-11e8-9d36-7f6ce129c644.png">

In Via however, `link.href` gets corrupted, and `normalizeURI` chokes on the result:

<img width="911" alt="via-mw-link" src="https://user-images.githubusercontent.com/2458/49542251-f4454f80-f8cc-11e8-98d2-eea3b0b8aa24.png">

I think the corruption is happening due to Via's client side JavaScript.

I was able to create a minimal repro. Serve the following HTML page and try to load the client into it:

```html
<html>
  <head>
    <link rel="foobar" href="http://mw-data:TemplateStyles:r123">
  </head>
  <body>

  </body>
</html>
```

Since it is perfectly possible for HTML out on the web to include this without Via's client-side JS mangling the link, the client definitely needs to be robust to this.

**Comment by robertknight** [comment] 2018-12-05 20:39
I should have searched for issues first. This is a duplicate of https://github.com/hypothesis/product-backlog/issues/742

**Closed** 2018-12-05 20:41 UTC
Labels: duplicate
