### ISSUE TITLE
Some PDFs that worked in a Canvas Files assignment stopped working, then worked again when the file name was changed

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#1448] opened 2020-02-08 19:08 UTC
Ticket:
https://hypothesis.zendesk.com/agent/tickets/8356

The issue:
U of Michigan uses our Canvas app, and on Friday multiple instructors reported that that assignments they had previously made and accessed were no longer accessible. There seems to be two different errors:

1) "Unexpected server response"

<img width="1438" alt="error 1" src="https://user-images.githubusercontent.com/22603275/74090495-efa09c00-4a79-11ea-91e5-c5138e905f4b.png">

This occurs when using the PDF "Study shows that students learn more when taking part in classrooms that employ active-learning strategies – Harvard Gazette.pdf". When I replicate the problem using this PDF, I get the following Console errors:
<img width="671" alt="Screen Shot 2020-02-08 at 1 51 56 PM" src="https://user-images.githubusercontent.com/22603275/74090523-3f7f6300-4a7a-11ea-94f7-869b248815fc.png">

The instructor said they solved this problem by renaming the file to "Harvard Gazette.doc". I replicated, renaming the file to "Harvard Gazette.pdf" and confirmed the assignment stopped giving the error.

2) "JWT rejected: resource claim does not match URL path” 
<img width="1362" alt="Screen Shot 2020-02-08 at 1 57 25 PM" src="https://user-images.githubusercontent.com/22603275/74090576-f67bde80-4a7a-11ea-878d-93902f328b99.png">

Error log that accompanies this screen shot:
[lms.hypothes.is-1581129730234.log](https://github.com/hypothesis/lms/files/4174981/lms.hypothes.is-1581129730234.log)

A different instructor, and their students, received this error on three different PDFs:

- Schmitter and Karl 1991, What Democracy is and is not.pdf
- Excerpts of Baviskar and Malone 2004, Canache 2012, Quaranta 2019.pdf
- Excerpts from Cheibub, Gandhi, and Vreeland 2010, Boix, Miller, and Rosato 2012, and Coppedge et al. 2011.pdf

I get the same error message, but different Console errors, when I try to replicate:
<img width="1320" alt="Screen Shot 2020-02-08 at 2 00 12 PM" src="https://user-images.githubusercontent.com/22603275/74090611-5a9ea280-4a7b-11ea-8c3c-6fe69473ced1.png">

Similar to the first problem, changing the name to "Dem is.pdf" for one of the docs made it work again, and I've been able to confirm this on my end.

Additional notes and files:

- The IT director says there have been "no documented changes" to their Canvas instance in the time between when files were working and when they stopped.
- The Canvas Dev key is on, and not scoped.
- I sent them a PDF that I knew worked for us, and it worked for them in a Canvas Files assignment.

Files:
[Excerpts from Cheibub, Gandhi, and Vreeland 2010, Boix, Miller, and Rosato 2012, and Coppedge et al. 2011.pdf](https://github.com/hypothesis/lms/files/4174996/Excerpts.from.Cheibub.Gandhi.and.Vreeland.2010.Boix.Miller.and.Rosato.2012.and.Coppedge.et.al.2011.pdf)
[Excerpts of Baviskar and Malone 2004, Canache 2012, Quaranta 2019.pdf](https://github.com/hypothesis/lms/files/4174997/Excerpts.of.Baviskar.and.Malone.2004.Canache.2012.Quaranta.2019.pdf)
[Schmitter and Karl 1991, What Democracy is and is not.pdf](https://github.com/hypothesis/lms/files/4174998/Schmitter.and.Karl.1991.What.Democracy.is.and.is.not.pdf)
[Study shows that students learn more when taking part in classrooms that employ active-learning strategies – Harvard Gazette.pdf](https://github.com/hypothesis/lms/files/4174999/Study.shows.that.students.learn.more.when.taking.part.in.classrooms.that.employ.active-learning.strategies.Harvard.Gazette.pdf)

**Comment by seanh** [comment] 2020-02-10 10:02
What lies behind the <kbd>More information</kbd> button in this screenshot is kind of crucial for debugging this, unfortunately:

<img width="1438" alt="error 1" src="https://user-images.githubusercontent.com/22603275/74090495-efa09c00-4a79-11ea-91e5-c5138e905f4b.png">

**Comment by seanh** [comment] 2020-02-10 10:16
@mkdir-washington-edu Can you provide step-by-step instructions for how to replicate the problem with the Harvard Gazette PDF file? I've been unable to replicate it

**Comment by seanh** [comment] 2020-02-10 10:17
Also for the "JWT rejected: resource claim does not match URL path”, we need instructions on how to replicate the problem

**Comment by seanh** [comment] 2020-02-10 10:18
Are we definitely sure that the users are using these files from Canvas Files, and not some other file storage?

**Comment by seanh** [comment] 2020-02-10 11:10
The fact that people were able to get around the error by renaming files suggests that a bad response had gotten into the browser or Cloudflare cache. Renaming the file would bust the cache

**Comment by jon-betts** [comment] 2020-02-10 14:36
We currently believe this is due to the PDF URL we are passed being a redirect to a another URL which actually serves the PDF. This much works, but we are telling browsers / Cloudflare to cache that redirect for 1 day.

The reason renaming the file likely works, is because it resets the clock. I would expect this to fail eventually too, at which point renaming it back will fix it for a time.

To address this we are going to release two changes:

 * The first is to disable caching entirely to stop the bleeding as soon as possible
 * The second is to check whether the thing we are proxying is a redirect, if so, we will disable the cache

The Via3 ticket for this is: https://github.com/hypothesis/via3/issues/98

**Comment by klemay** [comment] 2020-02-10 16:11
_Note: these steps worked for me on Friday evening, but as of Monday Feb 10 they no longer result in the error message for me._ 

## Steps taken to reproduce:
1. Log in to Canvas as a teacher
2. Upload one of the Canvas files linked to at the bottom of the first issue comment (we used [this one](https://github.com/hypothesis/lms/files/4174996/Excerpts.from.Cheibub.Gandhi.and.Vreeland.2010.Boix.Miller.and.Rosato.2012.and.Coppedge.et.al.2011.pdf))
3. Create an assignment with the Canvas file picker, using the PDF you've uploaded
4. Launch the assignment

## Expected results
The PDF loads with the Hypothesis sidebar 

## Actual results
See screenshot:
<img width="1432" alt="Screen Shot 2020-02-07 at 9 42 22 PM" src="https://user-images.githubusercontent.com/12087705/74166169-1edb1880-4bf4-11ea-941c-32d52da4e39a.png">

## Notes
We got the following information from the instructor and instructional designer:

- Assignments created with public URLs were working fine
- _Some_ assignments created using the Canvas file picker worked: in the instructor's course, her syllabus worked. The instructional designer was viewing assignments created with Canvas PDFs in other course sites and they worked. 
- We confirmed there were no issues with the Canvas installation or developer key (which we had predicted, since some Canvas Files assignments worked)
- We sent a PDF to the instructional designer which worked with Canvas Files in our instance - it also worked in the instructor's course site
- The instructor sent over the problematic PDFs, and they did not load properly when we created assignments in our Canvas instance following the instructions at the top of this comment.
- Renaming the PDFs and trying again to upload / create an assignment seemed to fix the issue for us and for the instructor - though the instructional designer noted that she had to shorten the file names significantly in order for it to work.  For example changing `Schmitter and Karl 1991, What Democracy is and is not.pdf` to `Schmitter and Karl What Democracy is and is not.pdf` did not work but `What Dem is.pdf` did work. Unclear whether it's the file name length, or just that the new file name has to be "different enough" from the original.

**Comment by seanh** [comment] 2020-02-11 11:40
I think the _JWT rejected: resource claim does not match URL path_ is caused by Canvas files with commas (or other special characters) in their filenames. I've opened a separate issue for it: https://github.com/hypothesis/via3/issues/106

**Comment by klemay** [comment] 2020-02-11 16:50
Closing in favor of https://github.com/hypothesis/via3/issues/106

**Closed by klemay** 2020-02-11 16:50 UTC
Labels: Bug
