### ISSUE TITLE
Public highlights show on HTML documents in LMS document

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#701] opened 2019-06-14 17:04 UTC
([Reported by a user in Zendesk](https://hypothesis.zendesk.com/agent/tickets/5270))

For HTML pages that have public annotations, those highlights are showing in the LMS app when the assignment is launched, even though the sidebar is scoped to a group. The annotations themselves don't show in the sidebar, but the highlighted text does, and it creates a distracting reading experience:

![screenshot-hypothesis instructure com-2019 06 14-12-54-24](https://user-images.githubusercontent.com/12087705/59525154-9e68ea00-8ea3-11e9-91de-9430e939da32.png)

...especially if there are a lot of Public annotations on the article:

![screenshot-hypothesis instructure com-2019 06 14-12-56-20](https://user-images.githubusercontent.com/12087705/59525253-e425b280-8ea3-11e9-9aba-227e146d8e5a.png)

The user first experienced this in Blackboard with the following URL: https://www.theatlantic.com/magazine/archive/2008/07/is-google-making-us-stupid/306868/

I know we have conflicts with the Atlantic already, so I decided to try with some other articles that have public annotations (I just found them at hypothes.is/search):

- https://bmccopenpedagogy.commons.gc.cuny.edu/agenda/
- https://www.cracked.com/blog/5-apocalypse-scenarios-you-should-stop-worrying-about/

I replicated the issue in Blackboard and Canvas, so it's not Blackboard-specific. 

For the Cracked article, when I launch the Hypothesis assignment in Canvas, my browser throws the following console errors:

<img width="1403" alt="Screen Shot 2019-06-14 at 1 01 32 PM" src="https://user-images.githubusercontent.com/12087705/59525541-9d848800-8ea4-11e9-819d-6c8f3dfa8f99.png">
<img width="1400" alt="Screen Shot 2019-06-14 at 1 01 47 PM" src="https://user-images.githubusercontent.com/12087705/59525547-a1180f00-8ea4-11e9-84e3-93565ae23f6d.png">
<img width="1402" alt="Screen Shot 2019-06-14 at 1 01 55 PM" src="https://user-images.githubusercontent.com/12087705/59525549-a412ff80-8ea4-11e9-8c7f-3914a79480d8.png">

You should be able to replicate this by going into our Canvas instance and launching this: 
https://hypothesis.instructure.com/courses/4/modules/items/826

**Comment by klemay** [comment] 2019-06-14 17:07
Not sure if this is related, but linking just in case: https://github.com/hypothesis/lms/issues/433

**Comment by robertknight** [comment] 2019-07-01 14:58
I was able to reproduce this issue by creating an assignment in Canvas with the URL set to https://www.theatlantic.com/magazine/archive/2008/07/is-google-making-us-stupid/306868/

The console logs contain warnings about there being multiple "Discovery servers" ... which means multiple sidebars, and I can see that is the case in the iframe tree shown in the Chrome dev tools. Looking at the network requests that get made, I see two sets of requests being made to the Hypothesis API, one with the expected authorization for the lms app and another with the authorization for my regular account, as if I was using Via directly.

Fixing Via so it doesn't inject Hypothesis into proxied iframes and/or fixing the client so it behaves in a more predictable way when there are multiple sidebars at difference places in the iframe tree would solve the problem, if that is what is going on here. Of the two issues, fixing Via is probably the easier thing to do, but I have highlighted fixing the Hypothesis client as something important to do in the next few months.

**Comment by robertknight** [comment] 2019-07-01 14:59
See also: https://github.com/hypothesis/client/issues/249 and https://github.com/hypothesis/client/issues/187

**Comment by judell** [comment] 2019-08-05 17:15
> Fixing Via so it doesn't inject Hypothesis into proxied iframes

https://github.com/hypothesis/via/pull/118 intended to stop that from happening, but evidently it didn't? https://github.com/hypothesis/via/issues/119

**Comment by ajpeddakotla** [comment] 2019-08-05 20:44
Issue has been added to the product and sprint pre-planning board. See slack discussion here: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1565023996031700

**Comment by robertknight** [comment] 2019-08-19 13:45
https://github.com/hypothesis/via/pull/171 is a bandaid fix in Via. The PR description contains a detailed explanation of why the problem happens. It is indeed due to the issue [mentioned above](https://github.com/hypothesis/lms/issues/701#issuecomment-507300767).

**Comment by robertknight** [comment] 2019-08-20 06:26
The issue has been resolved in Via, and thus the LMS app, via https://github.com/hypothesis/via/pull/171. As a bonus, the web pages that Katelyn linked to in the description now behave much better when viewed through Via alone.

The root issue in the client with frame discovery still exists, but will cause problems much less frequently now as it no longer happens in Via.

**Closed by robertknight** 2019-08-20 06:26 UTC
