### ISSUE TITLE
Write an initial plan for adding LTI 1.3 support

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3648] opened 2022-02-03 17:59 UTC
Come up with a plan for how we will add LTI 1.3 support.

See also:

* The [LTI 1.1 spec](https://www.imsglobal.org/specs/ltiv1p1p1/implementation-guide) (we need to continue supporting LTI 1.1 as well)
* The [LTI 1.3 spec](https://www.imsglobal.org/spec/lti/v1p3/)
* The LTI 1.3 [migration guide](https://www.imsglobal.org/spec/lti/v1p3/migr/)
* [Spike: what is the most basic possible implementation of LTI 1.3?](https://github.com/hypothesis/lms/issues/877)

**Comment by marcospri** [comment] 2022-03-02 13:07
Duplicate of #877 and superseded by a few spikes with the `LTI1.3` Feature

**Closed by marcospri** 2022-03-02 13:07 UTC
Labels: Backend
