### ISSUE TITLE
Make sure assignment launch succeeds even if assignment has no points possible

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#872] opened 2019-08-07 14:02 UTC
Reading through the [Canvas code](https://github.com/instructure/canvas-lms/blob/5b07c6445748e6884eb35b141ad080be39970b96/lib/basic_lti/basic_outcomes.rb#L259) that handles LTI Outcome Management requests to record a submission LTI launch URL, I found an issue where the request can fail if an assignment has its "Points" field set to an empty string.

(Note, the below applies only after https://github.com/hypothesis/lms/pull/867 is merged)

**Steps to reproduce**

1. Create an assignment as a teacher in Canvas
2. Launch the assignment as a student with SpeedGrader integration enabled
3. As the teacher, edit the assignment and change the Points field to be blank and save the result
4. Relaunch the assignment again

**Expected result:** Steps (2) and (4) both succeed
**Actual result:** The assignment launch in Step 4 fails in https://github.com/hypothesis/lms/pull/867
**Workaround:** The teacher can work around this by entering "0" as the points available, which is the default

Notes: If you edit the assignment again as a teacher after step (3), the "Points" box shows "0" even though you edited it to be blank in the previous change and this clearly had an effect.

**Comment by seanh** [comment] 2019-12-17 13:44
It required [taking advantage of a bug in Canvas](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1576588594033000?thread_ts=1576588302.031900&cid=C4K6M7P5E) to reproduce this and [that bug has now been fixed in Canvas](https://github.com/instructure/canvas-lms/commit/55a592a80b546181b30c2e0fa8a554174f6be671). I was unable to reproduce the issue today

**Closed by seanh** 2019-12-17 13:44 UTC
Labels: Bug, Canvas
