### ISSUE TITLE
Implement remaining modal dialog focus behavior

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#2038] opened 2020-08-20 10:16 UTC
The `Dialog` component used in the LMS frontend for modal dialogs doesn't currently implement all of the [standard focus behaviors](https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal) for modal dialogs. In particular:

1. When the dialog is closed, focus should be restored to the element that had focus before the dialog was opened, assuming it still exists
2. When using the Tab and Shift+Tab keys to navigate around the dialog, focus should be trapped within the dialog.

Point (1) is pretty easy to do. Point (2) is more complex. We might want to look at a dependency to handle this.

**Comment by lyzadanger** [comment] 2022-08-23 13:45
This is a dupe of https://github.com/hypothesis/frontend-shared/issues/77

**Closed by lyzadanger** 2022-08-23 13:45 UTC
Labels: Frontend
